### ISSUE TITLE
Gamepad displayed incorrectly

### ISSUE THREAD

**Issue by atesanec** [neonichu/MD.emu#2]
Hello,

I have noticed that both on iPhone and iPad virtual gamepad is displayed incorrectly (see screenshot below). Hope for your help

Best Regards,
Victor Ilinskiy
![IMG_5674](https://f.cloud.github.com/assets/2547674/63374/c1f99e8a-5dd4-11e2-8b78-932c46a8d457.PNG)

**Comment by eamonnfaherty** [comment]
the same is happening when I deploy to my iphone5 which is running ios 6.0.1

**Comment by ssh4net** [comment]
Same here, ipad 2 iOS 6.1.3

**Comment by ssh4net** [comment]
Find solution.
After open project in xcode.
Open resources folder, and change path for overlay64.png and overlay128.png from existing that going to NES controller. To MD.emu/MD.emu/res/overlays/
Also in MD.emu/MD.emu/res/ios you can find missed icons. But you need trim transparent pixels from some icons first, or xcode not allow use them.

Don't understand why this happen with source. Or new xcode broke something or source have some "fixes".

**Comment by neonichu** [comment]
This project is just a repackaging done by me, I will update to the newest upstream version soon, but I don't do any actual development on it.
