### ISSUE TITLE
xcode 4.6.3 on iphone 5 ios7 using ios6.1 sdk on screen control dislocated

### ISSUE THREAD

**Issue by hhhnz** [neonichu/MD.emu#4]
xcode 4.6.3 on iphone 5 ios7 using ios6.1 sdk on screen control dislocated. on screen control not working properly, and icade not works as well. Is this a pixel problem? Where can I modify it? Thanks.

**Comment by neonichu** [comment]
This project is just a repackaging done by me, I will update to the newest upstream version soon, but I don't do any actual development on it.
